### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by lucasgautheron** [ActionFPS/ActionFPS-Game#103]
```
stacktrace:
/home/lucas/Documents/Jeux/ActionFPS-Game/bin_unix/native_client() [0x4c406b]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7ff9d8e244b0]
/home/lucas/Documents/Jeux/ActionFPS-Game/bin_unix/native_client() [0x4801a0]
/home/lucas/Documents/Jeux/ActionFPS-Game/bin_unix/native_client() [0x47d2e5]
/home/lucas/Documents/Jeux/ActionFPS-Game/bin_unix/native_client() [0x47c9dd]
/home/lucas/Documents/Jeux/ActionFPS-Game/bin_unix/native_client() [0x47a3c1]
/home/lucas/Documents/Jeux/ActionFPS-Game/bin_unix/native_client() [0x4758df]
/home/lucas/Documents/Jeux/ActionFPS-Game/bin_unix/native_client() [0x475ce3]
/home/lucas/Documents/Jeux/ActionFPS-Game/bin_unix/native_client() [0x4b5cdf]
/home/lucas/Documents/Jeux/ActionFPS-Game/bin_unix/native_client() [0x46b260]
/home/lucas/Documents/Jeux/ActionFPS-Game/bin_unix/native_client(main+0x1004) [0x44ed44]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7ff9d8e0f830]
/home/lucas/Documents/Jeux/ActionFPS-Game/bin_unix/native_client() [0x40e929]
ActionFPS error (11) ()
OpenAL Error (A004): invalid operation, line 359
OpenAL Error (A004): invalid operation, line 359
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by lucasgautheron** [comment]
This is completely useless, should play a few games with -O0 and debug symbols.

**Comment by lucasgautheron** [comment]
```
w00p|Million: 1hp
w00p|Lucas sprayed eM|'quico
eM|'quico sprayed w00p|Drakas
player w00p|Lucas disconnected
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Thread 1 "native_client" received signal SIGABRT, Aborted.
0x00007ffff59e2428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: Aucun fichier ou dossier de ce type.
(gdb) backtrace
#0  0x00007ffff59e2428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff59e402a in __GI_abort () at abort.c:89
#2  0x00007ffff632484d in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff63226b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6322701 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6322919 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff6322ebc in operator new(unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff6322f19 in operator new[](unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x000000000043e7f2 in vector<discscore>::growbuf (
    this=0x7ca3b0 <discscores>, sz=67108865) at ./tools.h:511
#9  0x000000000043e5a4 in vector<discscore>::add (this=0x7ca3b0 <discscores>)
    at ./tools.h:458
#10 0x000000000043b30e in parsemessages (cn=-1, d=0x0, p=..., demo=true)
    at clients2c.cpp:906
#11 0x000000000043de1d in servertoclient (chan=1, buf=0xb0fdf80 "!\201Bk\f", 
    len=24, demo=true) at clients2c.cpp:1549
#12 0x000000000043de70 in localservertoclient (chan=1, 
---Type <return> to continue, or q <return> to quit---
    buf=0xb0fdf80 "!\201Bk\f", len=24, demo=true) at clients2c.cpp:1557
#13 0x00000000004caa49 in sendpacket (n=0, chan=1, packet=0xb34dbe0, 
    exclude=-1, demopacket=true) at server.cpp:114
#14 0x00000000004ca993 in sendpacket (n=-1, chan=1, packet=0xb34dbe0, 
    exclude=-1, demopacket=true) at server.cpp:102
#15 0x00000000004d00a4 in readdemo () at server.cpp:831
#16 0x00000000004e4779 in serverslice (timeout=0) at server.cpp:3986
#17 0x0000000000470b95 in main (argc=4, argv=0x7fffffffdbf8) at main.cpp:1468
(gdb) 
```

**Comment by ScalaWilliam** [comment]
@lucasgautheron would you please upload the .dmo here? @gyunderscorebe may be able to look at it.

**Comment by lucasgautheron** [comment]
Duplicate of #123
