### ISSUE TITLE
Crash in our testing

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#123]
# Bug
Part of #98 work.
## Why this is a problem
Crash experienced on all clients at once - common logic problem
## Why this is an important problem
Could prevent adoption and thus prevents us from making an official release.
## Expected behavior
No crash
## Actual behavior
Crashed all players at once during a game
## Steps to reproduce behavior
@lucasgautheron  has downloaded a demo for it

https://cdn.discordapp.com/attachments/231380080591372288/277820781344456715/20170204_1434_62.210.131.155_ac_elevation_15min_CTF.dmo

**Comment by lucasgautheron** [comment]
https://cdn.discordapp.com/attachments/231380080591372288/277820781344456715/20170204_1434_62.210.131.155_ac_elevation_15min_CTF.dmo

**Comment by lucasgautheron** [comment]
Just crashed right after voting mastermode match

**Comment by lucasgautheron** [comment]
```
w00p|Million: 1hp
w00p|Lucas sprayed eM|'quico
eM|'quico sprayed w00p|Drakas
player w00p|Lucas disconnected
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Thread 1 "native_client" received signal SIGABRT, Aborted.
0x00007ffff59e2428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: Aucun fichier ou dossier de ce type.
(gdb) backtrace
#0  0x00007ffff59e2428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff59e402a in __GI_abort () at abort.c:89
#2  0x00007ffff632484d in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff63226b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6322701 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6322919 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff6322ebc in operator new(unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff6322f19 in operator new[](unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x000000000043e7f2 in vector<discscore>::growbuf (
    this=0x7ca3b0 <discscores>, sz=67108865) at ./tools.h:511
#9  0x000000000043e5a4 in vector<discscore>::add (this=0x7ca3b0 <discscores>)
    at ./tools.h:458
#10 0x000000000043b30e in parsemessages (cn=-1, d=0x0, p=..., demo=true)
    at clients2c.cpp:906
#11 0x000000000043de1d in servertoclient (chan=1, buf=0xb0fdf80 "!\201Bk\f", 
    len=24, demo=true) at clients2c.cpp:1549
#12 0x000000000043de70 in localservertoclient (chan=1, 
---Type <return> to continue, or q <return> to quit---
    buf=0xb0fdf80 "!\201Bk\f", len=24, demo=true) at clients2c.cpp:1557
#13 0x00000000004caa49 in sendpacket (n=0, chan=1, packet=0xb34dbe0, 
    exclude=-1, demopacket=true) at server.cpp:114
#14 0x00000000004ca993 in sendpacket (n=-1, chan=1, packet=0xb34dbe0, 
    exclude=-1, demopacket=true) at server.cpp:102
#15 0x00000000004d00a4 in readdemo () at server.cpp:831
#16 0x00000000004e4779 in serverslice (timeout=0) at server.cpp:3986
#17 0x0000000000470b95 in main (argc=4, argv=0x7fffffffdbf8) at main.cpp:1468
(gdb) 
```

**Comment by lucasgautheron** [comment]
Fixed
